services:
  - type: web
    name: easyapply-bot
    plan: free
    env: docker
    dockerfilePath: ./Dockerfile
    # No buildCommand or startCommand needed, handled by Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: CHROME_BINARY
        value: /usr/bin/chromium